### ISSUE TITLE
Could not load type 'CommandDotNet.IoCExtension' from assembly 'CommandDotNet, Version=2.8.1.0

### ISSUE THREAD

**Issue by dotnetshadow** [bilal-fazlani/commanddotnet#160] opened 2019-07-29 04:32 UTC
Hi there,

This is possibly linked to this issue
https://github.com/bilal-fazlani/commanddotnet/issues/143

Perhaps the change wasn't reverted? 
I used the new syntax and it worked. Not sure which syntax will be used going forward?

```
Exception: System.TypeLoadException: Could not load type 'CommandDotNet.IoCExtension' from assembly 'CommandDotNet, Version=2.8.1.0, Culture=neutral, PublicKeyToken=null'.
 at CommandDotNet.IoC.MicrosoftDependencyInjection.Extension.UseMicrosoftDependencyInjection[T](AppRunner`1 appRunner, IServiceProvider serviceProvider)
Exception Message:   Could not load type 'CommandDotNet.IoCExtension' from assembly 'CommandDotNet, Version=2.8.1.0, Culture=neutral, PublicKeyToken=null'.
Exception Source:    CommandDotNet.IoC.MicrosoftDependencyInjection.Extension.UseMicrosoftDependencyInjection - CommandDotNet.AppRunner`1[T] UseMicrosoftDependencyInjection[T](CommandDotNet.AppRunner`1[T], System.IServiceProvider)
```

**Comment by bilal-fazlani** [comment] 2019-07-29 06:14
Hi, @dotnetshadow ,
What version of `CommandDotNet.IoC.MicrosoftDependencyInjection` are you using?

**Comment by dotnetshadow** [comment] 2019-07-29 06:45
Version 1.0.9

**Comment by bilal-fazlani** [comment] 2019-07-29 17:01
@dotnetshadow I have updated the dependencies. Not sure if that was the cause. https://www.nuget.org/packages/CommandDotNet.IoC.MicrosoftDependencyInjection/1.1.0

If this is still not fixed, could you please describe - which syntax works exactly and which one causes exception

**Comment by dotnetshadow** [comment] 2019-08-13 01:18
Sorry my laptop died haven't had a chance to check this, I'll definitely check this week and report back

**Comment by bilal-fazlani** [comment] 2019-08-18 04:33
Awesome. Thanks for raising the issue. Closing this ticket now.

**Closed by bilal-fazlani** 2019-08-18 04:33 UTC
