### ISSUE TITLE
Properties from base class are not inherited for IArgumentModel derived class

### ISSUE THREAD

**Issue by NecroFilja** [bilal-fazlani/commanddotnet#184] opened 2020-01-21 09:25 UTC
We have 2 similar commands: update and create.
We created 2 classes - CreateParameters, UpdateParameters.
So create method look like:
```
[ApplicationMetadata(Name = "create", Description = "Creates new entity.")]
public Task<int> CreateAsync(CreateParameters options)
```

to not copy paste common properties for CreateParameters, UpdateParameters we created CommonParameters class:

```
 public class CommonParameters : IArgumentModel
    {
        [Option(
            LongName = "audit",
            Description = "",
            Inherited = true)]
        public bool IsItemAuditEnabled { get; set; }
  }
public class CreateParameters: CommonParameters 
```
the problem is that CommonParameters  properties are not seen by framework.
We assume Inherited=true could help, but it is not true. 

I checked the code for ArgumentInfoCreator.GetArgumentsFromModel and than 
TypeExtensions.GetDeclaredProperties and it uses reflection following way:
`type.GetProperties(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public)`

which means no inheritance possible.  I think it will be nice if we could inherit model, espceially for complex commands.

**Comment by drewburlingame** [comment] 2020-01-24 13:53
Hi @NecroFilja thanks for posting the issue.  

The framework was designed to [favor composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) as much as possible.  You achieve this through composition as:

```
public class CreateParameters: IArgumentModel
{
  public CommonParameters CommonParameters { get; set; }
  /* other Create specific arguments */
}
```

If you don't have additional arguments to define for Create or Update, then I'd recommend using `CommonParameters ` in the method definition to remove the extra clicks to find the actual parameters.

If you feel strongly about using inheritance for this, please submit a PR with tests.

**Comment by drewburlingame** [comment] 2020-01-26 20:57
Since there's a way to compose the arguments, I'll close this ticket.  If you want to submit a PR, you can re-open.

**Closed by drewburlingame** 2020-01-26 20:57 UTC
